package com.shov.coreui.ui.themes

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF2e5da8)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFd6e2ff)
val md_theme_light_onPrimaryContainer = Color(0xFF001a41)
val md_theme_light_secondary = Color(0xFF565e71)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFdae2f9)
val md_theme_light_onSecondaryContainer = Color(0xFF131c2c)
val md_theme_light_tertiary = Color(0xFF705574)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFfad7fc)
val md_theme_light_onTertiaryContainer = Color(0xFF29132e)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfdfbff)
val md_theme_light_onBackground = Color(0xFF1a1b1f)
val md_theme_light_surface = Color(0xFFfdfbff)
val md_theme_light_onSurface = Color(0xFF1a1b1f)
val md_theme_light_surfaceVariant = Color(0xFFe0e2ec)
val md_theme_light_onSurfaceVariant = Color(0xFF44474f)
val md_theme_light_outline = Color(0xFF74777f)
val md_theme_light_inverseOnSurface = Color(0xFFf2f0f4)
val md_theme_light_inverseSurface = Color(0xFF2f3034)
val md_theme_light_inversePrimary = Color(0xFFaac7ff)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFaac7ff)
val md_theme_dark_onPrimary = Color(0xFF002e68)
val md_theme_dark_primaryContainer = Color(0xFF08458e)
val md_theme_dark_onPrimaryContainer = Color(0xFFd6e2ff)
val md_theme_dark_secondary = Color(0xFFbec6dc)
val md_theme_dark_onSecondary = Color(0xFF283041)
val md_theme_dark_secondaryContainer = Color(0xFF3f4759)
val md_theme_dark_onSecondaryContainer = Color(0xFFdae2f9)
val md_theme_dark_tertiary = Color(0xFFddbcdf)
val md_theme_dark_onTertiary = Color(0xFF3f2843)
val md_theme_dark_tertiaryContainer = Color(0xFF573e5b)
val md_theme_dark_onTertiaryContainer = Color(0xFFfad7fc)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1a1b1f)
val md_theme_dark_onBackground = Color(0xFFe4e2e6)
val md_theme_dark_surface = Color(0xFF1a1b1f)
val md_theme_dark_onSurface = Color(0xFFe4e2e6)
val md_theme_dark_surfaceVariant = Color(0xFF44474f)
val md_theme_dark_onSurfaceVariant = Color(0xFFc4c6d0)
val md_theme_dark_outline = Color(0xFF8e9099)
val md_theme_dark_inverseOnSurface = Color(0xFF1a1b1f)
val md_theme_dark_inverseSurface = Color(0xFFe4e2e6)
val md_theme_dark_inversePrimary = Color(0xFF2e5da8)
val md_theme_dark_shadow = Color(0xFF000000)

val seed = Color(0xFFacc7ff)
val error = Color(0xFFba1b1b)
