name: Bump Versions

on:
  push:
    branches:
    - dev/CreateRelease
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Get label using Check PR Labels on Push
      uses: shioyang/check-pr-labels-on-push-action@v1.0.3
      with:
        github-token: ${{ secrets.GITHUBTOKEN }}
        labels: '["small","medium","large"]'
    - name: See result
      run: echo "${{ steps.check_pr_labels.outputs.result }}"

