name: Build project

on:
  push:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Get Key
      env:
        ENCODED_STRING: ${{ secrets.KEY_B64 }}
      run: echo $ENCODED_STRING | base64 -di > ${{ github.workspace }}/Key.jks
    - name: get BuildProperties
      run: echo -e '${{secrets.BUILD_PROPERTIES_KT}}' > ${{ github.workspace }}/buildSrc/src/main/kotlin/BuildProperties.kt
    - name: get online drivers keys
      run: echo -e '${{secrets.KEYS}}' > ${{ github.workspace }}/app/src/main/java/com/shov/unlimstorage/values/Keys.kt
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Build project
      run: ./gradlew build
