name: Android CI

on:
  push:
    branches: [master,dev/BoxSignIn]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: get key
      run: echo "${{secrets.KEY}}" > Key.jks
    - name: get properties
      run: echo '${{secrets.BUILD_PROPERTIES_KT}}' > buildSrc/src/main/kotlin/BuildProperties.kt
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build Debug APK
      run: ./gradlew assembleDebug
    - name: Releasing using Hub
      uses: ShaunLWM/action-release-debugapk@master
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
       APP_FOLDER: app
       RELEASE_TITLE: New Build
