name: Release APK

on:
  push:
    branches:
    - main
    - dev/CreateRelease
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Get Key
      uses: timheuer/base64-to-file@v1
      with:
        fileName: 'Key.jks'
        encodedString: ${{secrets.KEY_B64}}
    - name: get BuildProperties
      run: echo -e '${{secrets.BUILD_PROPERTIES_KT}}' > ${{ github.workspace }}/buildSrc/src/main/kotlin/BuildProperties.kt
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build Debug APK
      run: ./gradlew assembleDebug
    - name: Releasing using Hub
      uses: actions/upload-artifact@master
      with:
        release_name: Release ${{github.ref}}
        name: release.apk
        path: '${{ github.workspace }}/app/build/outputs/apk/release/app-release.apk'
