name: Release APK

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: get key
      run: echo $KEY > Key.jks
      shell: bash
      env:
        KEY: ${{secrets.KEY}}
    - name: get BuildProperties.kt
      run: echo $BUILDPROPERIES > ${{ github.workspace }}/buildSrc/src/main/kotlin/BuildProperties.kt
      shell: bash
      env:
        BUILDPROPERTIES: ${{secrets.BUILDPROPERTIES_KT}}
    - name: Show BuildProperties
      run: cat ${{ github.workspace }}/buildSrc/src/main/kotlin/BuildProperties.kt
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build Debug APK
      run: ./gradlew assembleDebug
    - name: Chek path
      run: |
        ls
        cd '${{ github.workspace }}/app/build/outputs/apk/release'
        ls
    - name: Releasing using Hub
      uses: actions/upload-artifact@master
      with:
       release_name: Release ${{github.ref}}
       name: release.apk
       path: '${{ github.workspace }}/app/build/outputs/apk/release/app-release.apk'
