name: Release APK

on:
  push:
    branches:
    - main
    - dev/CreateRelease
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Get Key
      env:
        ENCODED_STRING: ${{ secrets.KEY_B64 }}
      run: echo $ENCODED_STRING | base64 -di > ${{ github.workspace }}/Key.jks
    - name: get BuildProperties
      run: echo -e '${{secrets.BUILD_PROPERTIES_KT}}' > ${{ github.workspace }}/buildSrc/src/main/kotlin/BuildProperties.kt
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build Debug APK
      run: ./gradlew assembleDebug
    - name: Create release
      uses: actions/create-release@master
      env:
        GITHUB_TOKEN: ${{secrets.GITHUBTOKEN}}
      with:
        tag_name: Release
        release_name: Release ${{github.ref}}
        name: release.apk
    - name: Create release and upload apk
      uses: underwindfall/create-release-with-debugapk@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
      with:
        asset_path: '${{ github.workspace }}/app/build/outputs/apk/release/app-release.apk'
        asset_name: Unlim_storage.apk
        asset_content_type: application/apk
